name: First_workflow
on:
  workflow_dispatch
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "heloo everyone"
      - name: print goodbye
        run: echo "goodbye"


